services:
  - type: web
    name: Dermisyn-backend
    runtime: python
    buildCommand: "pip install torch==2.1.2+cpu torchvision==0.16.2+cpu --extra-index-url https://download.pytorch.org/whl/cpu && pip install -r backend/requirements.txt"
    startCommand: "cd backend && gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: PORT
        value: 5000
